name: Java CI

on: [push]

jobs:
  build-full:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn --batch-mode --show-version verify
